---
title: "DUF23"
output: github_document
author: "Devon Birdseye"
date: "03/27/20"
---
#Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
set.seed(586)
```
```{r}
library(reshape2)
library(tidyverse)
library(ggplot2)
```

#CoMPP
```{r}
compp <- read.csv("Nb13373_CoMPP.csv", stringsAsFactors = F)
compp.m <- melt(compp)
colnames(compp.m) <- c("mAb", "sample", "value")
compp.m$treatment <- c(rep("CDTA", 88),rep("NaOH", 88))
compp.m$mAb <- factor(compp.m$mAb, levels=unique(compp.m$mAb))
compp.m$treatment <- factor(compp.m$treatment, levels=unique(compp.m$treatment))
compp.m$sample <- rep(c(rep("Control.1", 22), rep("Control.2", 22), rep("Nb13373.1",22), rep("Nb13373.2",22)),2)
```

```{r}
ggplot(data = compp.m, aes(x=mAb, y=sample, fill=value)) +
  geom_tile(color="white") + 
  scale_fill_gradient(low = "white", high = "red") + 
  geom_text(aes(label = value), size=3)+
  coord_flip()+
  theme_minimal()+
  facet_wrap(~treatment)+
  theme(axis.text.y = element_text(size=9, color = "black"),
        axis.text.x = element_text(size=9, angle = 35, hjust = .9, color = "black"),
        axis.title.y = element_blank(),
        aspect.ratio = 3,
        legend.position = "none")
ggsave("Fig_Nb13373_CoMPP.png", dpi = 300)
```

#ELISA
```{r}
elisa <- read.csv("ELISA_gsrOE.csv",stringsAsFactors = F)
elisa$mAb <- paste(elisa$mAb, ": ", elisa$epitope)
elisa <- elisa[,-2]
elisa.m <- melt(elisa)
colnames(elisa.m) <- c("mAb", "sample", "value") 
elisa.m$treatment <- c(rep("ammonium oxalate", 46), rep("sodium carbonate", 46), rep("1M KOH", 46), rep("4M KOH", 46))
elisa.m$mAb <- factor(elisa.m$mAb, levels=unique(elisa.m$mAb))
elisa.m$treatment <- factor(elisa.m$treatment, levels=unique(elisa.m$treatment))
elisa.m$sample <- rep(c(rep("Col-0", 23), rep("35S:GSR-YFP", 23)), 4)
```


```{r}
ggplot(data = elisa.m, aes(x=mAb, y=sample, fill=value)) +
  geom_tile(color="white") + 
  scale_fill_gradient(low = "white", high = "red") + 
  geom_text(aes(label = value), size=2)+
  coord_flip()+
  theme_minimal()+
  facet_wrap(~treatment, nrow = 1)+
  theme(text = element_text(size=8),
        axis.text.y = element_text(color = "black"),
        axis.text.x = element_text(angle = 35, hjust = .9, color = "black"),
        axis.title = element_blank(),
        aspect.ratio = 4,
        legend.position = "none")

ggsave("Fig_DUF23OE_ELISA.png", dpi = 300)
```

#HPAEC
```{r read in hpaec data}
hpaec <- read.csv("180424_DUF23_HPAEC.csv", stringsAsFactors = F)
```
```{r calculate mol ratios}
hpaec$sum <- rowSums(hpaec[,3:12])
hpaec$Fucose.sum <- hpaec$Fucose/hpaec$sum
hpaec$Rhamnose.sum <- hpaec$Rhamnose/hpaec$sum
hpaec$Arabinose.sum <- hpaec$Arabinose/hpaec$sum
hpaec$Glucosamine.sum <- hpaec$Glucosamine/hpaec$sum
hpaec$Galactose.sum <- hpaec$Galactose/hpaec$sum
hpaec$Glucose.sum <- hpaec$Glucose/hpaec$sum
hpaec$Xylose.sum <- hpaec$Xylose/hpaec$sum
hpaec$Mannose.sum <- hpaec$Mannose/hpaec$sum
hpaec$GalA.sum <- hpaec$GalA/hpaec$sum
hpaec$GlcA.sum <- hpaec$GlcA/hpaec$sum
```
```{r split into dfs by genotype}
hpaec.split <- split.data.frame(hpaec, f = hpaec$genotype)
```
```{r calculate averages}
#define new (empty) dataframe
hpaec.avg <- data.frame(matrix(NA, nrow = 9, ncol = 10))
colnames(hpaec.avg) <- as.character(colnames(hpaec)[3:12])
rownames(hpaec.avg) <- unique(hpaec$genotype)
#populate dataframe with averages
for(i in 1:length(hpaec.split)){
hpaec.avg[i,] <- colSums(hpaec.split[[i]][,14:23])
}
```
```{r calculate standard deviation}
#define new (empty) dataframe
hpaec.sd <- data.frame(matrix(NA, nrow = 9, ncol = 10))
colnames(hpaec.sd) <- as.character(colnames(hpaec)[3:12])
rownames(hpaec.sd) <- unique(hpaec$genotype)
#populate dataframe with averages
for(i in 1:length(hpaec.split)){
hpaec.sd[i,] <- apply(hpaec.split[[i]][,14:23], 2, sd)
}
```

```{r combine avg and sd into single dataframe}
hpaec.avg$genotype <- rownames(hpaec.avg)
hpaec.sd$genotype <- rownames(hpaec.sd)

hpaec.avg <- melt(hpaec.avg)
hpaec.sd <- melt(hpaec.sd)

colnames(hpaec.avg) <- c("genotype", "sugar", "avg")
colnames(hpaec.sd) <- c("genotype", "sugar", "sd")

hpaec.avg$id <- 1:nrow(hpaec.avg)
hpaec.sd$id <- 1:nrow(hpaec.sd)
```
```{r}
hpaec.avg.sd <- merge.data.frame(hpaec.avg, hpaec.sd[,c("id", "sd")], by.x = "id", by.y = "id")
hpaec.avg.sd
```


```{r plot hpaec data}
ggplot(hpaec.avg.sd, mapping = aes(x=sugar, y=avg, fill=genotype))+
  geom_col(position = "dodge")+
  scale_fill_manual(values=c("#000000","#009292","#ff6db6","#24ff24",
 "#490092","#db6d00","#b66dff","#920000","#b6dbff"))+
  geom_errorbar(aes(ymin=avg-sd, ymax=avg+sd), width=.2,
                 position=position_dodge(.9))+
  theme_bw()+
  ylab("mol%")+
  theme(axis.text.x = element_text(angle=45, hjust = 1.1))
ggsave("180424_DUF23_HPAEC.png", width = 7, height = 6)
```




